# Generated by Django 2.1.5 on 2020-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Endpoint')),
                ('url', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Fecha de Modificacion')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
